services:
  api1:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
      - DEBUG=true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:8080" 
    command: ["bun", "run", "dev"]

  api2:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
      - DEBUG=true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3002:8080"
    command: ["bun", "run", "dev"]

  postgres:
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: rinha_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro

  redis:
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - backend
