services:
  api1: &api-service
    container_name: api1
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      - SERVER_SOCKET_PATH=/tmp/api1.sock
    volumes:
      - .:/app
      - socket_data:/tmp
    command: ['bun', 'run', 'dev']
    networks:
      - backend
      - payment-processor
    depends_on:
      - memorydb
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '140MB'

  api2:
    <<: *api-service
    container_name: api2
    environment:
      - SERVER_SOCKET_PATH=/tmp/api2.sock

  memorydb:
    container_name: memorydb
    build:
      context: .
      dockerfile: Dockerfile.memorydb
      target: development
    env_file:
      - .env
    volumes:
      - .:/app
      - socket_data:/tmp
    command: ['bun', '--watch', 'run', 'src/db-server/index.ts']
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '15MB'

  nginx:
    container_name: nginx
    image: nginx:alpine
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - socket_data:/tmp
    depends_on:
      - api1
      - api2
    networks:
      - backend
    ports:
      - '9999:80'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '55MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  socket_data:
