services:
  api1: &api-service
    build:
      context: .
      target: ${BUILD_TARGET:-production}
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - PAYMENT_PROCESSOR_URL_DEFAULT=${PAYMENT_PROCESSOR_URL_DEFAULT}
      - PAYMENT_PROCESSOR_URL_FALLBACK=${PAYMENT_PROCESSOR_URL_FALLBACK}
    networks:
      - backend
      - payment-processor
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "180MB"

  api2:
    <<: *api-service

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "150MB"

  redis:
    image: redis:alpine
    command: redis-server --maxmemory 125mb --maxmemory-policy allkeys-lru
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "125MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres_data:
