services:
  api1: &api-service
    build:
      context: .
      target: development
    environment:
      - BUN_ENV=development
      - BUILD_TARGET=development
      - DEBUG=true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:8080" 
    command: ["bun", "run", "dev"]

  api2:
    <<: *api-service
    ports:
      - "3002:8080"

  nginx:
    ports:
      - "9999:80"

  postgres:
    ports:
      - "5432:5432" 

  redis:
    ports:
      - "6379:6379"
