services:
  api1:
    build:
      context: .
      target: development
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:8080" 
    command: ["bun", "run", "dev"]

  api2:
    build:
      context: .
      target: development
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3002:8080"
    command: ["bun", "run", "dev"]

  postgres:
    env_file:
      - .env.dev
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    ports:
      - "6379:6379"
