services:
  api-1: &api-service
    container_name: api-1
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      - SERVER_SOCKET_PATH=/tmp/api_1.sock
    volumes:
      - .:/app
      - socket_data:/tmp
    command: ['bun', 'run', 'dev']
    networks:
      - backend
      - payment-processor
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.675'
          memory: '135MB'

  api-2:
    <<: *api-service
    container_name: api-2
    environment:
      - SERVER_SOCKET_PATH=/tmp/api_2.sock

  database:
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile.database
      target: development
    env_file:
      - .env
    volumes:
      - .:/app
      - socket_data:/tmp
    command: ['bun', '--watch', 'run', 'src/db-server/index.ts']
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '50MB'

  balancer:
    container_name: balancer
    image: nginx:alpine
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - socket_data:/tmp
    depends_on:
      - api-1
      - api-2
    networks:
      - backend
    ports:
      - '9999:80'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '30MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  socket_data:
