services:
  api1: &api-service
    build:
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/app
      - memorydb_data:/app/data
    ports:
      - '3001:8080'
    command: ['bun', 'run', 'dev']
    networks:
      - backend
      - payment-processor
    depends_on:
      - memorydb
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '120MB'

  api2:
    <<: *api-service
    ports:
      - '3002:8080'

  memorydb:
    build:
      context: .
      dockerfile: Dockerfile.memorydb
    volumes:
      - memorydb_data:/app/data
    networks:
      - backend
    ports:
      - '8081:8081'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '90MB'

  nginx:
    image: nginx:alpine
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
    ports:
      - '9999:80'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '20MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  memorydb_data:
