services:
  api1: &api-service
    build:
      context: .
      target: ${BUILD_TARGET:-production}
    env_file:
      - .env
    environment:
      - BUN_ENV=development
      - BUILD_TARGET=development
      - DEBUG=true
    networks:
      - backend
      - payment-processor
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "180MB"

  api2:
    <<: *api-service

  nginx:
    image: nginx:alpine
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "150MB"

  redis:
    image: redis:alpine
    command: redis-server --maxmemory 125mb --maxmemory-policy allkeys-lru
    env_file:
      - .env
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "125MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres_data:
