services:
  api1: &api-service
    build:
      context: .
      target: production
    environment:
      - BUN_ENV=production
      - BUILD_TARGET=production
      - DEBUG=false
    restart: unless-stopped

  api2:
    <<: *api-service

  nginx:
    restart: unless-stopped

  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped
