services:
  write_api: &api-service
    container_name: write_api
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      - SERVER_SOCKET_PATH=/tmp/write_api.sock
    volumes:
      - .:/app
      - socket_data:/tmp
    command: ['bun', 'run', 'dev']
    networks:
      - backend
      - payment-processor
    depends_on:
      - memorydb
    deploy:
      resources:
        limits:
          cpus: '1.1'
          memory: '240MB'

  read_api:
    <<: *api-service
    container_name: read_api
    environment:
      - SERVER_SOCKET_PATH=/tmp/read_api.sock
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '40MB'

  memorydb:
    container_name: memorydb
    build:
      context: .
      dockerfile: Dockerfile.memorydb
      target: development
    env_file:
      - .env
    volumes:
      - .:/app
      - socket_data:/tmp
    command: ['bun', '--watch', 'run', 'src/db-server/index.ts']
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '15MB'

  nginx:
    container_name: nginx
    image: nginx:alpine
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - socket_data:/tmp
    depends_on:
      - write_api
      - read_api
    networks:
      - backend
    ports:
      - '9999:80'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '55MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  socket_data:
